<MyGridLayout>
    GridLayout:
        cols: 1

        GridLayout:
            cols: 2
            Label:
                text: "Name"
            TextInput:
                multiline: False

            Label:
                text: "Color"
            TextInput:
                multiline: False

            Label:
                text: "Pizza"
            TextInput:
                multiline: False

        Button:
            text: "Submit"
