<MyGridLayout>
    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 2
            Label:
                text: "Name"
            TextInput:
                multiline: False

            Label:
                text: "Color"
            TextInput:
                multiline: False

            Label:
                text: "Pizza"
            TextInput:
                multiline: False

        Button:
            text: "Submit"
