<Button>
    font_size: 65
    background_normal: ''
    background_color: (0,0,1,1)

<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        padding: 50
        spacing: 20

        Button:
            text: "hello"

        Button:
            text: "there"

        Button:
            text: "mate"
            pos_hint: {'center_x': .5}
            size_hint: (.5, .5)